name: google_ml_kit_example
description: Demonstrates how to use the google_ml_kit plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.5+3
  camera: ^0.10.0
  path_provider: ^2.0.11

  #  google_ml_kit:
  #    path: ../
  #  google_mlkit_commons:
  #    path: ../../google_mlkit_commons
  google_mlkit_pose_detection:
    path: assets/google_mlkit_pose_detection

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/ml/
